;;; Time-stamp: "2009-09-24 22:20:48 mad"
;;; GNU Emacs 23.1.1 (i686-pc-linux-gnu, GTK+ Version 2.14.7)
;;; of 2009-08-02 on home

(add-to-list 'load-path "~/.emacs.d/init")

(load "init-default")
(load "init-custom")
(load "init-keybinding")

(load "init-progmode")
(load "init-c")
(load "init-elisp")
(load "init-bison")
(load "init-flex")
(load "init-js2")
(load "init-lua")
(load "init-php")
(load "init-prolog")
(load "init-as")

(load "init-cedet")
(load "init-ecb")
(load "init-yasnippet")
(load "init-flymake")
(load "init-gtags")
(load "init-gtk-look")
(load "init-pymacs")
(load "init-diff")
(load "init-ediff")
(load "init-magit")
(load "init-sr-speedbar")
(load "init-company")

(load "init-org")
(load "init-ditta")
(load "init-dired")
(load "init-elscreen")
(load "init-irfc")
(load "init-markdown")
(load "init-auctex")
(load "init-preview-latex")
(load "init-muttrc")
(load "init-osd")
(load "init-slackware")

(load "init-emms")
(load "init-jabber")
(load "init-juick")
(load "init-twitter")
(load "init-identica")
(load "init-vkontakte")
(load "init-google")
(load "init-pastebin")
(load "init-tv")
(load "init-w3m")
(load "init-sdcv")

(load "init-personal")
